/* eslint-disable no-shadow */
enum Techs {
  Docker = "Docker",
  Angular = "Angular 9+",
  NextJS = "NextJS",
  HTML5 = "HTML5",
  CSS3 = "CSS3",
  Sass = "Sass",
  Bootstrap = "Bootstrap",
  Javascript = "Javascript",
  Typescript = "Typescript",
  NodeJS = "NodeJS",
  ReactNative = "React Native",
  GitGitHub = "Git/Github",
  PythonDjango = "Python/Django",
  TailwindCSS = "TailwindCSS",
  StoryBook = "StoryBook",
  Jest = "Jest",
}
export enum DescTechs {
  HTML5Desc = "Utilizo diariamente para deixar estrutura e SEO de uma maneira correta.",
  CSS3Desc = "Utilizo diariamente para deixar meus projetos com um carinha mais bonita.",
  SASSDesc = "O dinamismo que o SASS traz faz com que eu o utilize muito em meus projetos pessoais.",
  BootstrapDesc = "Utilizo bastante quando quero algo mais depressa, por mais que ainda utilize muito o SASS e CSS puro.",
  TypescriptDesc = "Venho utilizando muito atualmente junto com NextJSTipar as coisas é muito importante e uso hoje no meu dia a dia.",
  NodeJSDesc = "Utilizo node frequentemente juntamente com o express para criação de API's básicas para complemento com o front-end.",
  NextJSDesc = "O que mais estudo e utilizo atualmente. NextJS é a tecnologia front-end que mais me divirto em utilizar.",
  StoryBookDesc = "Documentar componentes é algo muito importante e o storybook é uma ferramenta ótima para isso.",
  ReactNativeDesc = "Tive algumas experiências com React Native a um tempo, mas, não é algo que mais estou vendo hoje em dia. Mas, adorei usá-lo por um tempo juntamente com o Expo no meu celular e Android Studio",
  GitDesc = "Utilizo diariamente para networking, pes quisa de bibliotecas, armazenamento de projetos pessoais e etc. Também tenho conhecimento de workflows para CI/CD usando Github Actions.",
  DockerDesc = "Tive noções básicas anteriormente, mas, não é algo que estou utilizando atualmente. Mas, é uma tecnologia incrível e que gostaria muito de voltar a estudar.",
  PythonDjangoDesc = "Trabalhei anteriormente por 3 anos usando Django e Python. Foi uma experiência incrível e que me fez crescer muito como programador.",
  TailwindCSSDesc = "Estou estudando atualmente e gostando muito. No começo achei que não iria gostar por parecer CSS inline, porém, agora estou gostando pela rapidez de criar CSS e customizar com o que gostaria pro meu projeto/design.",
  JestDesc = "Testar é algo muito importante e o Jest é uma ferramenta incrível para isso. Uso em conjunto com NextJS e também já utilizei no Angular (apesar de Jasmine e Karma ser o padrão)",
}
export default Techs;
